- hosts: all
  gather_facts: true
  become: true

  roles:
    - docker
    - env
    - docker_network
    - database
    - app
    - proxy

- name: Move env file to proper place
  copy:
    remote_src: true
    src: /tmp/.env
    dest: /tmp/db.env
