name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - main
      - develop 
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

      #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21 
          # installe Java JDK version 21 (Temurin est une distribution OpenJDK).

      #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn -f TP1/tp-postgres/simpleapi/pom.xml clean verify
# lance la commande Maven mvn clean verify
# Ca va nettoyer les anciens builds, compiler l’application et lancer les tests unitaires et d’intégration.
# clean sert à supprimer les fichiers générés par les builds précédents, verify exécute les tests et vérifie que le projet est valide.
  # define job to build and publish docker image
build-and-push-docker-image:
  needs: test-backend
  # run only when code is compiling and tests are passing
  runs-on: ubuntu-24.04

  # steps to perform in job
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

    - name: Build image and push database
      uses: docker/build-push-action@v6
      with:
        context: ./database
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-db:latest

    - name: Build image and push httpd
      uses: docker/build-push-action@v6
      with:
        context: ./httpd
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-httpd:latest
